perfect-RoR/samples/12/03/form_object_sample/config/routes.rb
Rails.application.routes.draw do
  resources :user_registrations, only: %i[create new] do
    collection do
      get :completed
    end
  end

  get "terms", to: "pages#terms"
end

perfect-RoR/samples/12/03/form_object_sample/app/models/user.rb
# == Schema Information
#
# Table name: users
#
#  id              :bigint           not null, primary key
#  email           :string           not null
#  password_digest :string           not null
#  created_at      :datetime         not null
#  updated_at      :datetime         not null
#
# Indexes
#
#  index_users_on_email  (email) UNIQUE
#

class User < ApplicationRecord
  has_secure_password

  validates :email, email: true, uniqueness: true
  validates :password, format: { with: /\A[\p{ascii}&&[^\x20]]{8,72}\z/, allow_nil: true }
end

perfect-RoR/samples/12/03/form_object_sample/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  helper_method :current_user, :user_signed_in?

  private

  def current_user
    @current_user ||= User.find_by(id: session[:user_id]) if session[:user_id].present?
  end

  def sign_in(user)
    session[:user_id] = user.id
  end

  def user_signed_in?
    !current_user.nil?
  end
end

perfect-RoR/samples/12/03/form_object_sample/app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def terms; end
end

perfect-RoR/samples/12/03/form_object_sample/app/controllers/user_registrations_controller.rb
class UserRegistrationsController < ApplicationController
  def new
    @user_registration_form = UserRegistrationForm.new
  end

  def create
    @user_registration_form = UserRegistrationForm.new(user_registration_form_params)

    if @user_registration_form.save
      sign_in(@user_registration_form.user)
      redirect_to action: :completed
    else
      render :new
    end
  end

  def completed; end

  private

  def user_registration_form_params
    params.require(:user_registration_form).permit(
      :email,
      :password,
      :password_confirmation,
      :terms_of_service
    )
  end
end

perfect-RoR/samples/12/03/form_object_sample/app/helpers/pages_helper.rb
module PagesHelper
end

perfect-RoR/samples/12/03/form_object_sample/app/helpers/user_registrations_helper.rb
module UserRegistrationsHelper
end

perfect-RoR/samples/12/03/form_object_sample/app/views/pages/terms.html.erb
<h1>Pages#terms</h1>
<p>Find me in app/views/pages/terms.html.erb</p>

perfect-RoR/samples/12/03/form_object_sample/app/views/user_registrations/completed.html.erb
<h1>User was successfully registered.</h1>

perfect-RoR/samples/12/03/form_object_sample/app/views/user_registrations/new.html.erb
<h1>New User Registration</h1>

<%= form_with(model: @user_registration_form, url: user_registrations_path, local: true) do |form| %>
  <% if @user_registration_form.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user_registration_form.errors.count, "error") %> prohibited this user from being registered:</h2>

      <ul>
        <% @user_registration_form.errors.full_messages.each do |message| %>
          <li><%= message %></li>
        <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= form.label :email %>
    <%= form.email_field :email %>
  </div>

  <div class="field">
    <%= form.label :password %>
    <%= form.password_field :password %>
  </div>

  <div class="field">
    <%= form.label :password_confirmation %>
    <%= form.password_field :password_confirmation %>
  </div>

  <div class="field">
    <%= form.label :terms_of_service do %>
      <%= form.check_box :terms_of_service %>
      I accept the <%= link_to "Terms of Service", terms_path %>.
    <% end %>
  </div>

  <div class="actions">
    <%= form.submit "Submit" %>
  </div>
<% end %>